name: "Docker build and push"

on: 
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: axion-ui
      IMAGE_TAG: v1
      ACR_NAME: akacr1212134
      ACR_LOGIN_SERVER: akacr1212134.azurecr.io
  
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0

    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: 124a393a-1bcd-4f1e-a82a-7aafb702c031
        tenant-id: 7c23c5b4-ee12-4a85-a703-3cdda6279e4b
        subscription-id: 34382dad-4d83-4e06-9eeb-c20a9624d946

    - name: Login to ACR
      run: |
        az acr login --name $ACR_NAME

    - name: Build docker image
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG .

    - name: Tag image with ACR
      run: |
        docker tag $IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

    - name: image push to ACR
      run: |
        docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
